"""The follow-up drafter must sell the lane the prospect is actually in.

The creator lane (Twitch streamers, $400/mo clip retainer) and the ad-creative lane (DTC founders,
$650 drop / $950/mo) share a drafter. Guzu and MISTERARTHER got first touches on 2026-09-19 with
follow-ups dated 09-22 and 09-26, and every one of them would have been generated by a prompt that
says Alex sells ad creative and told the model to reason about "their ad account".

CREATOR_VOICE is built by substitution on AD_VOICE, and a str.replace that matches nothing does
nothing and says nothing — so these tests assert the substitutions actually landed, not just that
the constant exists.
"""
import os
import sys

sys.path.insert(0, os.path.expanduser("~/second-brain/scripts"))
import splitframe_daily as sd  # noqa: E402


def test_the_creator_voice_is_not_just_a_copy_of_the_ad_voice():
    assert sd.CREATOR_VOICE != sd.AD_VOICE


def test_the_creator_voice_quotes_the_clip_retainer_price():
    assert "$400/mo" in sd.CREATOR_VOICE
    assert "3 clips a week" in sd.CREATOR_VOICE


def test_the_creator_voice_never_mentions_the_ad_creative_offer():
    for wrong in ("$650", "$950", "ad-creative service", "DTC brands"):
        assert wrong not in sd.CREATOR_VOICE, f"creator prompt still sells {wrong}"


def test_the_creator_voice_does_not_reason_about_an_ad_account():
    # A Twitch streamer has no ad account. This is the line that would have produced nonsense.
    low = sd.CREATOR_VOICE.lower()
    assert "ad account" not in low
    assert "state the current state of their ads" not in low


def test_the_creator_hard_constraint_is_about_streams_instead():
    assert "watched their streams or VODs" in sd.CREATOR_VOICE
    # the anti-fabrication rule must survive the swap, not be dropped by it
    assert "HARD CONSTRAINT" in sd.CREATOR_VOICE
    assert "invent numbers" in sd.CREATOR_VOICE


def test_the_shared_craft_rules_survive_in_both():
    # 2026-09-25 follow-up audit: follow-ups are 35-80 words now (the 60-110 rule produced
    # "the math" emails), and the touch count lives in FU2_DAYS/no touch 4, not in the prompt.
    for voice in (sd.AD_VOICE, sd.CREATOR_VOICE):
        assert "35-80 words" in voice
        assert 'Return STRICT JSON' in voice
        assert "Ends flat" in voice


def test_a_creator_row_routes_to_the_creator_voice():
    assert sd.voice_for({"category": "creator"}) is sd.CREATOR_VOICE
    assert sd.voice_for({"category": "Creator"}) is sd.CREATOR_VOICE


def test_everything_else_keeps_the_ad_voice():
    for row in ({"category": "swimwear"}, {"category": ""}, {}, None):
        assert sd.voice_for(row) is sd.AD_VOICE


def test_the_real_creator_prospects_route_correctly():
    """The two live ones, read from the tracker rather than assumed."""
    rows = [r for r in sd.tracker_rows() if r.get("brand") in ("Guzu", "MISTERARTHER")]
    assert rows, "expected Guzu and MISTERARTHER in the tracker"
    for r in rows:
        assert sd.voice_for(r) is sd.CREATOR_VOICE, f"{r['brand']} would be pitched ad creative"


# ---------------------------------------------------------------------------
# parse_body: a truncated generation must never become an email.
#
# Reproduced live on Guzu touch 2, 2026-09-19. The model's reply hit max_tokens, so it had no
# closing brace; parse_body's prose fallback returned the raw text; the body began `{"body": "` and
# stopped mid-sentence. 45 words — comfortably over MIN_BODY_WORDS — and no fabrication tells, so
# every guard downstream reported a healthy draft.
# ---------------------------------------------------------------------------

TRUNCATED = ('{"body": "Did the math on the six hours a day thing. Say five days a week, that\'s '
             "thirty hours of vod. Three clips a week barely scratches what's actually in there. "
             "If you want, I'll cut one clip free, no card, no commitment, just so")


def test_a_truncated_generation_is_rejected_not_sent():
    assert sd.parse_body(TRUNCATED) == ""


def test_the_old_failure_shape_can_no_longer_reach_a_prospect():
    out = sd.parse_body(TRUNCATED)
    assert not out.lstrip().startswith('{"body"')
    # the gate that used to pass it
    assert len(out.split()) < sd.MIN_BODY_WORDS


def test_well_formed_json_still_parses():
    assert sd.parse_body('{"body": "Ran the math. Thirteen cuts a month."}') == \
        "Ran the math. Thirteen cuts a month."


def test_json_in_a_fenced_block_still_parses():
    assert sd.parse_body('```json\n{"body": "Short and clean."}\n```') == "Short and clean."


def test_json_after_a_preamble_still_parses():
    # The original reason the strict json.loads was abandoned; must keep working.
    assert sd.parse_body('Here you go:\n{"body": "Kept it short."}') == "Kept it short."


def test_plain_prose_is_still_accepted():
    # The model sometimes ignores the JSON instruction entirely. That reply is usable and must not
    # be thrown away by the new rejection path.
    prose = "Ran the math on the six hours a day thing. Thirty hours of vod a week."
    assert sd.parse_body(prose) == prose


def test_prose_mentioning_a_brace_is_not_mistaken_for_broken_json():
    prose = "Your overlay shows {viewers} instead of the count. Small thing, easy fix."
    assert sd.parse_body(prose) == prose
